"""Add_SistemaConfig_Fix

Revision ID: 87959e43485d
Revises: b57c6b0ca4e2
Create Date: 2026-07-13 12:53:39.779974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87959e43485d'
down_revision: Union[str, None] = 'b57c6b0ca4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sistema_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('openrouter_key', sa.Text(), nullable=True),
    sa.Column('openrouter_model', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('empresas', 'openrouter_key')
    op.drop_column('empresas', 'openrouter_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('openrouter_model', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('empresas', sa.Column('openrouter_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('sistema_config')
    # ### end Alembic commands ###
