"""Add config fields from setup

Revision ID: 9ebbfcfea7b1
Revises: ab4a2fba24fe
Create Date: 2026-07-06 14:45:09.209521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebbfcfea7b1'
down_revision: Union[str, None] = 'ab4a2fba24fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('pais', sa.String(length=100), nullable=True))
    op.add_column('empresas', sa.Column('fuso_horario', sa.String(length=100), nullable=True))
    op.add_column('empresas', sa.Column('moeda', sa.String(length=10), nullable=True))
    op.add_column('empresas', sa.Column('idioma', sa.String(length=10), nullable=True))
    op.add_column('empresas', sa.Column('setor', sa.String(length=100), nullable=True))
    op.add_column('empresas', sa.Column('cor_marca', sa.String(length=20), nullable=True))
    op.add_column('empresas', sa.Column('subdominio', sa.String(length=100), nullable=True))
    op.add_column('empresas', sa.Column('dominio_personalizado', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('whatsapp_conectado', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('empresas', sa.Column('telegram_conectado', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('empresas', sa.Column('stripe_publishable_key', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('stripe_secret_key', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('pagamento_modo_teste', sa.Boolean(), server_default='true', nullable=False))
    op.create_unique_constraint(None, 'empresas', ['subdominio'])
    op.create_unique_constraint(None, 'empresas', ['dominio_personalizado'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'empresas', type_='unique')
    op.drop_constraint(None, 'empresas', type_='unique')
    op.drop_column('empresas', 'pagamento_modo_teste')
    op.drop_column('empresas', 'stripe_secret_key')
    op.drop_column('empresas', 'stripe_publishable_key')
    op.drop_column('empresas', 'telegram_conectado')
    op.drop_column('empresas', 'whatsapp_conectado')
    op.drop_column('empresas', 'dominio_personalizado')
    op.drop_column('empresas', 'subdominio')
    op.drop_column('empresas', 'cor_marca')
    op.drop_column('empresas', 'setor')
    op.drop_column('empresas', 'idioma')
    op.drop_column('empresas', 'moeda')
    op.drop_column('empresas', 'fuso_horario')
    op.drop_column('empresas', 'pais')
    # ### end Alembic commands ###
