"""Add visualizacoes

Revision ID: a1265e484e04
Revises: 9ebbfcfea7b1
Create Date: 2026-07-06 19:24:29.762920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1265e484e04'
down_revision: Union[str, None] = '9ebbfcfea7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('propostas', sa.Column('visualizacoes', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('propostas', 'visualizacoes')
    # ### end Alembic commands ###
