"""Add ai limits and public token

Revision ID: ab4a2fba24fe
Revises: 7f489a73fb3a
Create Date: 2026-06-26 14:07:24.318302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab4a2fba24fe'
down_revision: Union[str, None] = '7f489a73fb3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('ai_credits_used_today', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('empresas', sa.Column('ai_credits_limit', sa.Integer(), nullable=False, server_default='20'))
    op.add_column('empresas', sa.Column('ai_credits_last_reset', sa.Date(), nullable=True))
    op.add_column('propostas', sa.Column('token_publico', sa.UUID(), nullable=False, server_default=sa.text('gen_random_uuid()')))
    op.add_column('propostas', sa.Column('assinatura_ip', sa.String(length=45), nullable=True))
    op.add_column('propostas', sa.Column('assinatura_data', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'propostas', ['token_publico'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'propostas', type_='unique')
    op.drop_column('propostas', 'assinatura_data')
    op.drop_column('propostas', 'assinatura_ip')
    op.drop_column('propostas', 'token_publico')
    op.drop_column('empresas', 'ai_credits_last_reset')
    op.drop_column('empresas', 'ai_credits_limit')
    op.drop_column('empresas', 'ai_credits_used_today')
    # ### end Alembic commands ###
