"""add smtp fields

Revision ID: b57c6b0ca4e2
Revises: ed2480729582
Create Date: 2026-07-08 15:46:23.649792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57c6b0ca4e2'
down_revision: Union[str, None] = 'ed2480729582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('smtp_host', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('smtp_port', sa.Integer(), nullable=True))
    op.add_column('empresas', sa.Column('smtp_user', sa.String(length=255), nullable=True))
    op.add_column('empresas', sa.Column('smtp_password', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'smtp_password')
    op.drop_column('empresas', 'smtp_user')
    op.drop_column('empresas', 'smtp_port')
    op.drop_column('empresas', 'smtp_host')
    # ### end Alembic commands ###
