"""Add magic link to orcamentos

Revision ID: bd6b4f3672f9
Revises: ff5b78fc4d50
Create Date: 2026-07-06 20:39:28.492703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd6b4f3672f9'
down_revision: Union[str, None] = 'ff5b78fc4d50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orcamentos', sa.Column('visualizacoes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('orcamentos', sa.Column('token_publico', sa.UUID(), nullable=False))
    op.add_column('orcamentos', sa.Column('assinatura_ip', sa.String(length=45), nullable=True))
    op.add_column('orcamentos', sa.Column('assinatura_data', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'orcamentos', ['token_publico'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orcamentos', type_='unique')
    op.drop_column('orcamentos', 'assinatura_data')
    op.drop_column('orcamentos', 'assinatura_ip')
    op.drop_column('orcamentos', 'token_publico')
    op.drop_column('orcamentos', 'visualizacoes')
    # ### end Alembic commands ###
