"""add openrouter_key to empresa

Revision ID: c392a230099f
Revises: 9567fb1497ec
Create Date: 2026-06-10 22:40:09.041613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c392a230099f'
down_revision: Union[str, None] = '9567fb1497ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('openrouter_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'openrouter_key')
    # ### end Alembic commands ###
