"""add missing columns

Revision ID: cdc8d3e2fdba
Revises: 4e37053e2f40
Create Date: 2026-06-16 10:50:56.224348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdc8d3e2fdba'
down_revision: Union[str, None] = '4e37053e2f40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('openrouter_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresas', 'openrouter_model')
    # ### end Alembic commands ###
