"""add_admin_payment_fields

Revision ID: ed2480729582
Revises: bd6b4f3672f9
Create Date: 2026-07-07 13:17:31.056620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2480729582'
down_revision: Union[str, None] = 'bd6b4f3672f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('empresas', sa.Column('plano', sa.String(length=50), server_default='gratuito', nullable=False))
    op.add_column('empresas', sa.Column('status_pagamento', sa.String(length=50), server_default='em_dia', nullable=False))
    op.add_column('empresas', sa.Column('ativo', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('usuarios', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('usuarios', 'is_superuser',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('empresas', 'ativo')
    op.drop_column('empresas', 'status_pagamento')
    op.drop_column('empresas', 'plano')
    # ### end Alembic commands ###
