"""Add instrucoes_ia

Revision ID: ff5b78fc4d50
Revises: a1265e484e04
Create Date: 2026-07-06 19:48:29.850738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5b78fc4d50'
down_revision: Union[str, None] = 'a1265e484e04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servicos', sa.Column('instrucoes_ia', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('servicos', 'instrucoes_ia')
    # ### end Alembic commands ###
